### PR TITLE
Resolves #315: Fix getRunbookTestDetails return type

### LINKED ISSUE #315: Fix getRunbookTaskDetails return type

### PR DESCRIPTION
**Pull request by nksprzak**

### CODE REVIEW

File: src/sdk/model/org/disaster-recovery-runbook/disaster-recovery-runbook.ts [hunk 1]
```diff
@@ -251,11 +253,11 @@ export class DisasterRecoveryRunbook {
    * @param {string} taskUuid
    * @returns {Promise<Task>}
```
Comment (cfsnyder) [inline src/sdk/model/org/disaster-recovery-runbook/disaster-recovery-runbook.ts]: can you update this doc too?
